# Generated by Django 5.2.6 on 2026-03-25 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carowner',
            options={'verbose_name': 'Car owner', 'verbose_name_plural': '01. Car owners'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'FAQ', 'verbose_name_plural': '04. FAQ'},
        ),
        migrations.AlterModelOptions(
            name='mastercustomuser',
            options={'verbose_name': 'Master', 'verbose_name_plural': '02. Masters'},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'Owner', 'verbose_name_plural': 'Owners'},
        ),
        migrations.AlterModelOptions(
            name='userbalance',
            options={'ordering': ['-updated_at'], 'verbose_name': 'User balance', 'verbose_name_plural': '03. User balances'},
        ),
        migrations.AlterModelOptions(
            name='usersmscode',
            options={'ordering': ['-created_at'], 'verbose_name': 'SMS code', 'verbose_name_plural': 'SMS codes'},
        ),
        migrations.RenameIndex(
            model_name='emailverificationtoken',
            new_name='accounts_em_token_629d48_idx',
            old_name='accounts_em_token_i_7f8e9a_idx',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, help_text='Optional. Enter your address.', null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Optional. Upload your profile photo.', null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Optional. Enter your date of birth.', null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, help_text='Optional. Enter your description.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, help_text="Indicates whether this user's email is verified.", verbose_name='Email verified'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Optional. Latitude of your location.', max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Optional. Longitude of your location.', max_digits=10, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Optional. Enter your phone number.', max_length=15, null=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='private_id',
            field=models.CharField(blank=True, help_text='Unique 6-digit user identifier. Generated automatically.', max_length=6, null=True, unique=True, verbose_name='Private ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Optional. Enter your Telegram Chat ID for SMS.', max_length=50, null=True, verbose_name='Telegram Chat ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='email',
            field=models.EmailField(help_text='Snapshot of email this token was issued for.', max_length=254, verbose_name='Email to verify'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(help_text='Answer to the question', verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether to show question in list', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order (lower number = higher)', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(help_text='Frequently asked question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='userbalance',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current user balance', max_digits=10, verbose_name='Balance amount'),
        ),
        migrations.AlterField(
            model_name='userbalance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='userbalance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='userbalance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='usersmscode',
            name='code',
            field=models.CharField(help_text='Verification code', max_length=10, verbose_name='SMS code'),
        ),
        migrations.AlterField(
            model_name='usersmscode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='usersmscode',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who requested the code (if registered)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_codes', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='usersmscode',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Expires at'),
        ),
        migrations.AlterField(
            model_name='usersmscode',
            name='identifier',
            field=models.CharField(help_text='Phone number or email', max_length=255, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='usersmscode',
            name='identifier_type',
            field=models.CharField(choices=[('phone', 'Phone'), ('email', 'Email')], help_text='Identifier type: phone or email', max_length=10, verbose_name='Identifier type'),
        ),
        migrations.AlterField(
            model_name='usersmscode',
            name='is_used',
            field=models.BooleanField(default=False, help_text='Whether the code was used', verbose_name='Used'),
        ),
        migrations.AlterField(
            model_name='usersmscode',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Used at'),
        ),
    ]
