# Generated by Django 5.2.6 on 2026-03-25 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_carowner_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carowner',
            options={'verbose_name': 'Driver', 'verbose_name_plural': '01. Driver'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'FAQ', 'verbose_name_plural': '03. FAQ'},
        ),
    ]
