# Generated by Django 5.2.6 on 2026-04-06 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_appversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(db_index=True, help_text='FCM/APNs token; unique so one installation maps to one user at a time.', max_length=512, unique=True, verbose_name='Device token')),
                ('device_type', models.CharField(help_text='e.g. ios, android, web', max_length=32, verbose_name='Device type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User device',
                'verbose_name_plural': 'User devices',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', '-updated_at'], name='accounts_us_user_id_77592e_idx')],
            },
        ),
    ]
