# Generated by Django 5.2.6 on 2026-04-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_lat_lon_decimal_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevice',
            name='device_token',
            field=models.CharField(db_index=True, help_text='FCM/APNs token; unique so one installation maps to one user at a time.', max_length=512, verbose_name='Device token'),
        ),
    ]
