# Generated by Django 5.2.6 on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0019_alter_userdevice_device_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='is_active',
            field=models.BooleanField(
                default=True,
                help_text='If false, this device will not receive push notifications.',
                verbose_name='Active',
            ),
        ),
        migrations.AddConstraint(
            model_name='userdevice',
            constraint=models.UniqueConstraint(fields=('user',), name='uniq_userdevice_per_user'),
        ),
    ]

