# Generated by Django 5.0.7 on 2026-05-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_userdevice_is_active_unique_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', help_text='cus_… for saved cards / off-session charges (client).', max_length=64, verbose_name='Stripe customer id'),
        ),
    ]
