# Generated by Django 5.0.7 on 2026-06-05 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_emailverificationtoken_code'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emailverificationtoken',
            name='accounts_em_user_co_91a2b1_idx',
        ),
    ]
