# Generated by Django 5.0.7 on 2026-07-22 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_emailverificationtoken_accounts_em_user_co_91a2b1_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='workshop_compliance_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='Set once when both tools and licenses are first confirmed. Never cleared or overwritten — legal evidence that the master self-attested.', null=True, verbose_name='Workshop compliance confirmed at'),
        ),
        migrations.CreateModel(
            name='WorkshopComplianceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_tools_confirmed', models.BooleanField(verbose_name='Tools confirmed')),
                ('has_licenses_confirmed', models.BooleanField(verbose_name='Licenses confirmed')),
                ('confirmed_at', models.DateTimeField(db_index=True, verbose_name='Confirmed at')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, default='', max_length=512, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Logged at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workshop_compliance_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Workshop compliance audit log',
                'verbose_name_plural': 'Workshop compliance audit logs',
                'ordering': ['-confirmed_at', '-id'],
            },
        ),
    ]
