# Generated by Django 5.2.6 on 2026-03-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_alter_category_service_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_at'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='categories/icons/', verbose_name='Category icon'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Category name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='service_type',
            field=models.CharField(blank=True, default='', help_text='Common service type for linking by_order and by_master categories. Examples: Repair, Diagnostics, Replacement, Maintenance, Tire fitting, Painting, Body repair, Electrical, Air conditioning, Tuning, etc.', max_length=100, verbose_name='Service type'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type_category',
            field=models.CharField(choices=[('by_master', 'By master category'), ('by_car', 'By car category'), ('by_order', 'By order category')], max_length=255, verbose_name='Category type'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
