# Generated by Django 5.2.6 on 2026-03-25 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_remove_category_service_type_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Main category',
                'verbose_name_plural': 'Main categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('categories.category',),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Sub category',
                'verbose_name_plural': 'Sub categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('categories.category',),
        ),
    ]
