# Generated by Django 5.2 migration stub

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0012_alter_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_custom_request_entry',
            field=models.BooleanField(
                default=False,
                help_text='If True: drivers see this as the client-only “Custom Request” entry; masters never see it in the public category catalog. Attach this main category to custom-request orders server-side.',
                verbose_name='Custom request entry',
            ),
        ),
    ]
