# Generated by Django 5.2.6 on 2026-03-25 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_alter_car_options_alter_car_brand_alter_car_category_and_more'),
        ('categories', '0008_alter_category_options_alter_category_created_at_and_more'),
        ('master', '0020_alter_master_options_alter_masteremployee_options_and_more'),
        ('order', '0009_review_userrating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderservice',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order service', 'verbose_name_plural': 'Order services'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rating', 'verbose_name_plural': 'Ratings'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='scheduledorder',
            options={'ordering': ['scheduled_date', 'scheduled_time_start'], 'verbose_name': 'Scheduled order', 'verbose_name_plural': 'Scheduled orders (by date)'},
        ),
        migrations.AlterModelOptions(
            name='sosorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'SOS order', 'verbose_name_plural': 'SOS orders (emergency assistance)'},
        ),
        migrations.AlterModelOptions(
            name='userrating',
            options={'ordering': ['-average_rating'], 'verbose_name': 'User rating', 'verbose_name_plural': 'User ratings'},
        ),
        migrations.AlterField(
            model_name='order',
            name='car',
            field=models.ManyToManyField(related_name='orders', to='car.car', verbose_name='Car'),
        ),
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.ManyToManyField(related_name='orders', to='categories.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Order discount (percentage or amount)', max_digits=10, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='expiration_time',
            field=models.DateTimeField(blank=True, help_text='Order expiration time (1 day from creation)', null=True, verbose_name='Expiration time'),
        ),
        migrations.AlterField(
            model_name='order',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Location latitude', max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='order',
            name='location',
            field=models.TextField(help_text='Address or place description', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='order',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Location longitude', max_digits=10, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='order',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='master.master', verbose_name='Master'),
        ),
        migrations.AlterField(
            model_name='order',
            name='masters',
            field=models.ManyToManyField(blank=True, help_text='List of master users assigned to this order', related_name='assigned_orders', to=settings.AUTH_USER_MODEL, verbose_name='Masters (users)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('scheduled', 'Scheduled (by date)'), ('sos', 'SOS / Emergency')], default='scheduled', help_text='Scheduled - order by date, SOS - emergency assistance', max_length=20, verbose_name='Order type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('high', 'High')], default='low', max_length=20, verbose_name='Order priority'),
        ),
        migrations.AlterField(
            model_name='order',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='Visit date to master (for scheduled orders only)', null=True, verbose_name='Scheduled date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='scheduled_time_end',
            field=models.TimeField(blank=True, help_text='Visit end time (e.g. 11:00)', null=True, verbose_name='Visit end time'),
        ),
        migrations.AlterField(
            model_name='order',
            name='scheduled_time_start',
            field=models.TimeField(blank=True, help_text='Visit start time (e.g. 10:00)', null=True, verbose_name='Visit start time'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Order status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='text',
            field=models.TextField(help_text='Detailed description of the problem or service', verbose_name='Order description'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Added at'),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='master_service_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_services', to='master.masterserviceitems', verbose_name='Master service'),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_services', to='order.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.TextField(blank=True, help_text='Rating comment', null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='master.master', verbose_name='Master'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='order.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveIntegerField(help_text='Rating from 1 to 5', verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL, verbose_name='User (rater)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, help_text='Review text', null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='review',
            name='order',
            field=models.OneToOneField(help_text='Order this review belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='order.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(help_text='Rating from 1 to 5', verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(help_text='User who left the review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL, verbose_name='Review author'),
        ),
        migrations.AlterField(
            model_name='review',
            name='tag',
            field=models.CharField(choices=[('fast_work', 'Fast work'), ('no_overpay', 'No overpayment'), ('deadline', 'On time'), ('always_available', 'Always available'), ('individual_approach', 'Individual approach'), ('polite', 'Polite')], help_text='What you liked about the master work', max_length=50, verbose_name='Review tag'),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating based on all reviews', max_digits=3, verbose_name='Average rating'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
