# Generated by Django 5.2.6 on 2026-03-28 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_options_alter_orderservice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accepted_at',
            field=models.DateTimeField(blank=True, help_text='When a master accepted / was booked (for cancellation rules)', null=True, verbose_name='Accepted at'),
        ),
        migrations.AddField(
            model_name='order',
            name='location_source',
            field=models.CharField(choices=[('manual', 'Address text (coordinates optional)'), ('gps_profile', 'GPS from user profile (CustomUser lat/long)'), ('gps_custom', 'GPS coordinates sent by client')], default='manual', max_length=20, verbose_name='Location source'),
        ),
        migrations.AddField(
            model_name='order',
            name='parts_purchase_required',
            field=models.BooleanField(default=False, help_text='If true, master buys parts; client pays parts outside the app.', verbose_name='Parts purchase required'),
        ),
        migrations.AddField(
            model_name='order',
            name='preferred_time',
            field=models.TextField(blank=True, default='', help_text='Client preferred service time (free text or app-specific format)', verbose_name='Preferred time'),
        ),
        migrations.AlterField(
            model_name='order',
            name='location',
            field=models.TextField(blank=True, default='', help_text='Service address text; optional if GPS coordinates are provided', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('on_the_way', 'On the way'), ('arrived', 'Arrived'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Order status'),
        ),
        migrations.CreateModel(
            name='OrderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='order_images/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='order.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order image',
                'verbose_name_plural': 'Order images',
                'ordering': ['created_at'],
            },
        ),
    ]
