# Generated by Django 5.2.6 on 2026-04-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_remove_order_masters'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='master_response_deadline',
            field=models.DateTimeField(blank=True, help_text='Master must accept or decline before this time (e.g. 15 minutes from offer)', null=True, verbose_name='Master offer deadline'),
        ),
        migrations.AlterField(
            model_name='order',
            name='accepted_at',
            field=models.DateTimeField(blank=True, help_text='When the assigned master accepted the order (exact address visible after this)', null=True, verbose_name='Accepted at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='preferred_time',
            field=models.TextField(blank=True, default='', help_text='Client preferred service time (free text)', verbose_name='Preferred time'),
        ),
    ]
