# Generated by Django 5.2.6 on 2026-04-03 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0024_master_service_area'),
        ('order', '0013_tz_master_offer_privacy_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Arrived at'),
        ),
        migrations.AddField(
            model_name='order',
            name='client_penalty_free_cancel_unlocked',
            field=models.BooleanField(default=False, help_text='Set automatically after configured hours on the way; client cancel without penalty.', verbose_name='Client penalty-free cancel (2h on the way)'),
        ),
        migrations.AddField(
            model_name='order',
            name='on_the_way_at',
            field=models.DateTimeField(blank=True, help_text='When master marked status "on the way".', null=True, verbose_name='On the way at'),
        ),
        migrations.AddField(
            model_name='order',
            name='work_started_at',
            field=models.DateTimeField(blank=True, help_text='When master started job (in_progress) after arrival.', null=True, verbose_name='Work started at'),
        ),
        migrations.CreateModel(
            name='MasterOrderCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('client_request', 'Client request'), ('vehicle_unavailable', 'Vehicle unavailable'), ('duplicate', 'Duplicate order'), ('emergency', 'Emergency'), ('other', 'Other')], max_length=32, verbose_name='Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_cancellations', to='master.master', verbose_name='Master')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_cancellations', to='order.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Master order cancellation',
                'verbose_name_plural': 'Master order cancellations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderWorkCompletionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='order_work_completion/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_completion_images', to='order.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order work completion image',
                'verbose_name_plural': 'Order work completion images',
                'ordering': ['created_at'],
            },
        ),
    ]
