# Generated by Django 5.2.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_order_sos_offer_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_arrival_at',
            field=models.DateTimeField(
                blank=True,
                help_text='Expected arrival time (set on on_the_way from eta_minutes or explicit datetime).',
                null=True,
                verbose_name='Estimated arrival',
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='eta_minutes',
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text='Minutes until arrival committed when marking on the way.',
                null=True,
                verbose_name='ETA minutes',
            ),
        ),
    ]
