# Generated by Django 5.2.6 on 2026-04-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_order_eta_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledorder',
            options={'ordering': ['scheduled_date', 'scheduled_time_start'], 'verbose_name': 'Scheduled order', 'verbose_name_plural': 'Scheduled orders'},
        ),
        migrations.AlterField(
            model_name='order',
            name='sos_offer_index',
            field=models.PositiveSmallIntegerField(default=0, help_text='Current index in sos_offer_queue.', verbose_name='SOS offer index'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sos_offer_queue',
            field=models.JSONField(blank=True, default=list, help_text='SOS: ordered master IDs (nearest first) for sequential offers.', verbose_name='SOS offer queue (master IDs)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='tag',
            field=models.CharField(choices=[('fast_work', 'Fast work'), ('no_overpay', 'No overpayment'), ('deadline', 'On time'), ('always_available', 'Always available'), ('individual_approach', 'Individual approach'), ('polite', 'Polite'), ('late_or_delayed', 'Late / delays'), ('poor_quality', 'Poor quality of work'), ('overpriced', 'Overpriced'), ('unprofessional', 'Unprofessional behavior'), ('hard_to_reach', 'Hard to reach / poor communication'), ('other_issue', 'Other issue')], help_text='What best describes your experience (one tag)', max_length=50, verbose_name='Review tag'),
        ),
    ]
