# Generated by Django 5.2.6 on 2026-04-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_order_sos_declined_master_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sos_declined_master_ids',
            field=models.JSONField(blank=True, default=list, help_text='SOS broadcast: master IDs who declined while order still pending.', verbose_name='SOS declined master IDs'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sos_offer_index',
            field=models.PositiveSmallIntegerField(default=0, help_text='Legacy ring index; unused for broadcast SOS.', verbose_name='SOS offer index'),
        ),
    ]
