# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_alter_order_sos_declined_master_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='preferred_date',
            field=models.DateField(
                blank=True,
                help_text='Standard orders: visit day chosen by client (with preferred_time_start).',
                null=True,
                verbose_name='Preferred service date',
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='preferred_time_start',
            field=models.TimeField(
                blank=True,
                help_text='Standard: client-chosen slot start (POST). End is set by master after accept (PATCH).',
                null=True,
                verbose_name='Preferred time start',
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='preferred_time_end',
            field=models.TimeField(
                blank=True,
                help_text='Set by assigned master via PATCH when status is accepted.',
                null=True,
                verbose_name='Preferred time end',
            ),
        ),
    ]
