# Generated by Django 5.2.6 on 2026-04-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_custom_request_order_type_and_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=18, help_text='Location latitude', max_digits=22, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='order',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=18, help_text='Location longitude', max_digits=22, null=True, verbose_name='Longitude'),
        ),
    ]
