# Generated by Django 5.2.6 on 2026-04-11 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_remove_reviewimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRequestOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Custom request order',
                'verbose_name_plural': 'Custom request orders',
                'ordering': ['-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('order.order',),
        ),
    ]
