# Generated by Django 5.2.6 on 2026-04-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_custom_request_order_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completion_pin',
            field=models.CharField(blank=True, default='', help_text='4-digit code shown to the client during in_progress; master must submit it to complete.', max_length=4, verbose_name='Work completion PIN'),
        ),
        migrations.AddField(
            model_name='order',
            name='completion_pin_issued_at',
            field=models.DateTimeField(blank=True, help_text='When status became in_progress and the PIN was generated.', null=True, verbose_name='Completion PIN issued at'),
        ),
    ]
