# Generated by Django 5.2.6 on 2026-04-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_order_arrival_deadline_autocancel_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='custom_request_date',
            field=models.DateField(blank=True, help_text='Calendar day for the requested service (client local / request time zone).', null=True, verbose_name='Custom request date'),
        ),
    ]
