# Generated by Django 5.2.6 on 2026-04-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0035_order_chat_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='parts_purchase_required_json',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of parts the master may need to buy. Each item: { "vehicle_vin": "…", "part_name": "…", "is_address": true/false }.',
                verbose_name='Parts purchase required (items)',
            ),
        ),
    ]

