# Generated by Django 5.2.6 on 2026-04-27

from django.db import migrations, models


def backfill_order_numbers(apps, schema_editor):
    Order = apps.get_model('order', 'Order')
    # Use a deterministic-ish approach: ORD_0001..ORD_9999, skipping used.
    used = set(
        x
        for x in Order.objects.exclude(order_number__isnull=True).exclude(order_number='').values_list('order_number', flat=True)
        if isinstance(x, str) and x
    )
    n = 1
    for o in Order.objects.filter(order_number__isnull=True).only('id', 'order_number').iterator(chunk_size=500):
        # Keep compatibility if some rows were created with '' in earlier failed attempts.
        if getattr(o, 'order_number', None) == '':
            o.order_number = None
        while n <= 9999:
            code = f"ORD_{n:04d}"
            n += 1
            if code not in used:
                used.add(code)
                o.order_number = code
                o.save(update_fields=['order_number'])
                break


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0036_order_parts_purchase_required_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(
                blank=True,
                db_index=True,
                null=True,
                default=None,
                help_text='Auto-generated order code like ORD_1234',
                max_length=8,
                unique=True,
                verbose_name='Order number',
            ),
        ),
        migrations.RunPython(backfill_order_numbers, migrations.RunPython.noop),
    ]

