# Generated by Django 5.2.6 on 2026-05-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0037_order_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterOfferEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='sent', max_length=16, verbose_name='Offer status')),
                ('offered_at', models.DateTimeField(auto_now_add=True, verbose_name='Offered at')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Responded at')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_events', to='master.master', verbose_name='Master')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_events', to='order.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Master offer event',
                'verbose_name_plural': 'Master offer events',
                'ordering': ['-offered_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='masterofferevent',
            constraint=models.UniqueConstraint(fields=('master', 'order'), name='uniq_master_offer_event_master_order'),
        ),
    ]

