# Generated by Django 5.2.6 on 2026-05-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0038_master_offer_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='extra_money',
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text='Additional charges added after service selection (e.g. extra work/parts).',
                max_digits=12,
                verbose_name='Extra money',
            ),
        ),
        migrations.AddField(
            model_name='orderservice',
            name='count',
            field=models.PositiveIntegerField(
                default=1,
                help_text='How many times this service is applied within the order (per service item).',
                verbose_name='Count',
            ),
        ),
    ]

