# Generated by Django 5.0.7 on 2026-05-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0040_order_extra_money_request'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='orderextramoneyrequest',
            new_name='order_order_order_i_658ef5_idx',
            old_name='order_order__status_idx',
        ),
        migrations.RenameIndex(
            model_name='orderextramoneyrequest',
            new_name='order_order_master__250b4c_idx',
            old_name='order_master__status_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='average_max_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Optional: average/max price estimate range for the order (shown to client).', max_digits=12, null=True, verbose_name='Average max price'),
        ),
        migrations.AddField(
            model_name='order',
            name='average_min_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Optional: average/min price estimate range for the order (shown to client).', max_digits=12, null=True, verbose_name='Average min price'),
        ),
    ]
