# Generated by Django 5.0.7 on 2026-05-07 13:28

from decimal import Decimal

from django.db import migrations, models


def _backfill_average_price(apps, schema_editor):
    """
    Preserve existing data from average_min_price / average_max_price into average_price:
    - if both are present: (min + max) / 2
    - if only one is present: that value
    - else: keep null
    """
    Order = apps.get_model('order', 'Order')

    for o in Order.objects.all().only('id', 'average_min_price', 'average_max_price', 'average_price'):
        if o.average_price is not None:
            continue
        mn = getattr(o, 'average_min_price', None)
        mx = getattr(o, 'average_max_price', None)
        if mn is not None and mx is not None:
            o.average_price = (Decimal(str(mn)) + Decimal(str(mx))) / Decimal('2')
        elif mn is not None:
            o.average_price = mn
        elif mx is not None:
            o.average_price = mx
        else:
            continue
        o.save(update_fields=['average_price'])


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0041_rename_order_order__status_idx_order_order_order_i_658ef5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='average_price',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                help_text='Optional: average price estimate for the order (shown to client).',
                max_digits=12,
                null=True,
                verbose_name='Average price',
            ),
        ),
        migrations.RunPython(
            code=_backfill_average_price,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='order',
            name='average_max_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='average_min_price',
        ),
    ]
