# Generated by Django 5.0.7 on 2026-05-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0042_remove_order_average_max_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='average_service_name',
            field=models.CharField(blank=True, default=None, help_text='Optional: service name/label associated with average_price (shown to client).', max_length=255, null=True, verbose_name='Average service name'),
        ),
    ]
