# Generated by Django 5.0.7 on 2026-05-09 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0030_alter_lat_lon_decimal_precision'),
        ('order', '0043_order_average_service_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderServiceAddRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_json', models.JSONField(blank=True, default=list, help_text='List of items: { "master_service_item_id": <int>, "count": <int>=1.. }', verbose_name='Requested services (items)')),
                ('master_comment', models.TextField(blank=True, default='', help_text='Reason/description for adding services.', verbose_name='Master comment')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16, verbose_name='Status')),
                ('client_comment', models.TextField(blank=True, default='', help_text='Required when rejecting (reason).', verbose_name='Client comment')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Decided at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_add_requests', to='master.master', verbose_name='Master')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_add_requests', to='order.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order service add request',
                'verbose_name_plural': 'Order service add requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'status'], name='order_order_order_i_4e4970_idx'), models.Index(fields=['master', 'status'], name='order_order_master__124973_idx')],
            },
        ),
    ]
