# Generated by Django 5.0.7 on 2026-05-14 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0044_orderserviceaddrequest'),
        ('payment', '0001_stripe_and_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], default='cash', help_text='Cash: no Stripe capture on complete. Card: charge saved card (Connect destination when set).', max_length=16, verbose_name='Payment type'),
        ),
        migrations.AddField(
            model_name='order',
            name='saved_card',
            field=models.ForeignKey(blank=True, help_text='Client card used when payment_type=card.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='payment.savedcard', verbose_name='Saved card'),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_payment_amount_cents',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Stripe charged amount (minor units)'),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_payment_currency',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='Stripe charge currency'),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_payment_error',
            field=models.TextField(blank=True, default='', verbose_name='Stripe last error'),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Stripe PaymentIntent id'),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_payment_status',
            field=models.CharField(choices=[('not_applicable', 'Not applicable'), ('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='not_applicable', max_length=32, verbose_name='Stripe payment status'),
        ),
    ]
