# Generated by Django 5.0.7 on 2026-05-14 16:57

from django.db import migrations, models


def forwards_cash_to_card(apps, schema_editor):
    Order = apps.get_model('order', 'Order')
    Order.objects.filter(payment_type='cash').update(payment_type='card')


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0045_stripe_and_payment'),
    ]

    operations = [
        migrations.RunPython(forwards_cash_to_card, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(
                choices=[('card', 'Card')],
                default='card',
                help_text='Card only: charge on master complete via Stripe (Connect destination when set).',
                max_length=16,
                verbose_name='Payment type',
            ),
        ),
    ]
