# Generated by Django 5.0.7 on 2026-06-05 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0052_order_towing'),
    ]

    operations = [
        migrations.CreateModel(
            name='TowingOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Towing order',
                'verbose_name_plural': 'Towing orders',
                'ordering': ['-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('order.order',),
        ),
        migrations.RenameIndex(
            model_name='ordertimechangerequest',
            new_name='order_order_order_i_003a31_idx',
            old_name='order_time__order_i_6f0f0d_idx',
        ),
        migrations.RenameIndex(
            model_name='ordertimechangerequest',
            new_name='order_order_master__926ee9_idx',
            old_name='order_time__master__a2f0c1_idx',
        ),
    ]
