# Generated by Django 5.0.7 on 2026-06-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0053_towingorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderservice',
            name='fuel_type',
            field=models.CharField(
                blank=True,
                choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel')],
                help_text='Client-selected fuel type for Fuel Delivery lines (gasoline or diesel).',
                max_length=16,
                null=True,
                verbose_name='Fuel delivery type',
            ),
        ),
    ]
