# Generated by Django 5.0.7 on 2026-06-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0054_orderservice_fuel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fuel_delivery_type',
            field=models.CharField(
                blank=True,
                choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel')],
                help_text='Client-selected fuel for Fuel Delivery orders (gasoline or diesel).',
                max_length=16,
                null=True,
                verbose_name='Fuel delivery type',
            ),
        ),
    ]
