# Generated by Django 5.0.7 on 2026-07-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0060_order_stripe_charge_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tip_charge_attempt',
            field=models.PositiveIntegerField(default=1, help_text="Idempotency attempt for the tip charge. Increments after a failed tip charge so a later retry is not stuck replaying Stripe's cached decline.", verbose_name='Tip charge attempt'),
        ),
        migrations.AlterField(
            model_name='order',
            name='towing_trip_type',
            field=models.CharField(blank=True, help_text='local, long_distance, accident_recovery, motorcycle, or semi_truck — selected by driver at order creation.', max_length=32, null=True, verbose_name='Towing service type (snapshot)'),
        ),
    ]
