# Generated by Django 5.2.6 on 2026-03-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_alter_car_options_alter_car_brand_alter_car_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/images/', verbose_name='Car image'),
        ),
    ]
