# Generated by Django 5.0.7 on 2026-05-14 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_role', models.CharField(choices=[('client', 'Client (driver / order owner)'), ('master', 'Master (provider)')], default='client', max_length=16, verbose_name='Holder role')),
                ('stripe_payment_method_id', models.CharField(max_length=64, verbose_name='Stripe PM id')),
                ('stripe_customer_id', models.CharField(max_length=64, verbose_name='Stripe customer id')),
                ('brand', models.CharField(blank=True, default='', max_length=32, verbose_name='Brand')),
                ('last4', models.CharField(blank=True, default='', max_length=4, verbose_name='Last4')),
                ('exp_month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Exp month')),
                ('exp_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Exp year')),
                ('funding', models.CharField(blank=True, default='', max_length=16, verbose_name='Funding')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default card')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cards', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Saved card',
                'verbose_name_plural': 'Saved cards',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='savedcard',
            constraint=models.UniqueConstraint(fields=('user', 'stripe_payment_method_id'), name='uniq_savedcard_user_pm'),
        ),
    ]
