# Generated by Django 5.2.6 on 2026-03-25 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_alter_category_options_alter_category_created_at_and_more'),
        ('master', '0019_master_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master',
            options={'ordering': ['-created_at'], 'verbose_name': 'Master', 'verbose_name_plural': 'Masters'},
        ),
        migrations.AlterModelOptions(
            name='masteremployee',
            options={'ordering': ['added_at'], 'verbose_name': 'Workshop employee', 'verbose_name_plural': 'Workshop employees'},
        ),
        migrations.AlterModelOptions(
            name='masterimage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Master image', 'verbose_name_plural': 'Master images'},
        ),
        migrations.AlterModelOptions(
            name='masterservice',
            options={'ordering': ['-created_at'], 'verbose_name': 'Master service', 'verbose_name_plural': 'Master services'},
        ),
        migrations.AlterModelOptions(
            name='masterserviceitems',
            options={'ordering': ['-created_at'], 'verbose_name': 'Master service item', 'verbose_name_plural': 'Master service items'},
        ),
        migrations.AlterField(
            model_name='master',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='master',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Master balance'),
        ),
        migrations.AlterField(
            model_name='master',
            name='card_expiry_month',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Card expiry month'),
        ),
        migrations.AlterField(
            model_name='master',
            name='card_expiry_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Card expiry year'),
        ),
        migrations.AlterField(
            model_name='master',
            name='card_number',
            field=models.CharField(blank=True, max_length=19, verbose_name='Card number'),
        ),
        migrations.AlterField(
            model_name='master',
            name='category',
            field=models.ManyToManyField(related_name='master_categories', to='categories.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='master',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='master',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='master',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='master',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last activity'),
        ),
        migrations.AlterField(
            model_name='master',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='master',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='master',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Workshop name (e.g. "Auto Service Station")', max_length=255, verbose_name='Workshop name'),
        ),
        migrations.AlterField(
            model_name='master',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='master',
            name='reserved_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Reserved amount'),
        ),
        migrations.AlterField(
            model_name='master',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='master',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_profiles', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='master',
            name='working_time',
            field=models.CharField(default='', max_length=100, verbose_name='Working hours'),
        ),
        migrations.AlterField(
            model_name='masteremployee',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Added at'),
        ),
        migrations.AlterField(
            model_name='masteremployee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_employments', to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='masteremployee',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='master.master', verbose_name='Master'),
        ),
        migrations.AlterField(
            model_name='masterimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Added at'),
        ),
        migrations.AlterField(
            model_name='masterimage',
            name='image',
            field=models.ImageField(upload_to='master_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='masterimage',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_images', to='master.master', verbose_name='Master'),
        ),
        migrations.AlterField(
            model_name='masterimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='masterservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Added at'),
        ),
        migrations.AlterField(
            model_name='masterservice',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_services', to='master.master', verbose_name='Master'),
        ),
        migrations.AlterField(
            model_name='masterserviceitems',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_service_items', to='categories.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='masterserviceitems',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Added at'),
        ),
        migrations.AlterField(
            model_name='masterserviceitems',
            name='master_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_service_items', to='master.masterservice', verbose_name='Master service'),
        ),
        migrations.AlterField(
            model_name='masterserviceitems',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Service name'),
        ),
        migrations.AlterField(
            model_name='masterserviceitems',
            name='price_from',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price from'),
        ),
        migrations.AlterField(
            model_name='masterserviceitems',
            name='price_to',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price to'),
        ),
        migrations.AlterField(
            model_name='masterserviceitems',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
