# Generated by Django 5.2.6 on 2026-03-25 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0020_alter_master_options_alter_masteremployee_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='master',
            name='card_cvv',
        ),
        migrations.RemoveField(
            model_name='master',
            name='card_expiry_month',
        ),
        migrations.RemoveField(
            model_name='master',
            name='card_expiry_year',
        ),
        migrations.RemoveField(
            model_name='master',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='master',
            name='reserved_amount',
        ),
        migrations.DeleteModel(
            name='MasterEmployee',
        ),
    ]
