# Generated by Django 5.2.6 on 2026-03-25 19:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def dedupe_service_items_and_set_price(apps, schema_editor):
    MasterServiceItems = apps.get_model('master', 'MasterServiceItems')
    OrderService = apps.get_model('order', 'OrderService')

    seen = {}
    for item in MasterServiceItems.objects.all().order_by('id'):
        key = (item.master_service_id, item.category_id)
        if key not in seen:
            pf = getattr(item, 'price_from', None)
            price = pf if pf is not None else Decimal('0')
            item.price = price
            item.save(update_fields=['price'])
            seen[key] = item.id
        else:
            keep_id = seen[key]
            OrderService.objects.filter(master_service_item_id=item.id).update(master_service_item_id=keep_id)
            item.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_maincategory_subcategory_proxies'),
        ('master', '0021_remove_master_finance_cards_and_employee'),
        ('order', '0010_alter_order_options_alter_orderservice_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterBusySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Start time')),
                ('end_time', models.TimeField(verbose_name='End time')),
                ('reason', models.CharField(blank=True, help_text='Optional note for manual blocks', max_length=255, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Master busy slot',
                'verbose_name_plural': 'Master busy slots',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='MasterScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Start time')),
                ('end_time', models.TimeField(verbose_name='End time')),
            ],
            options={
                'verbose_name': 'Master schedule day',
                'verbose_name_plural': 'Master schedule days',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='masterserviceitems',
            name='price',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Price',
            ),
        ),
        migrations.RunPython(dedupe_service_items_and_set_price, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='masterserviceitems',
            name='name',
        ),
        migrations.RemoveField(
            model_name='masterserviceitems',
            name='price_from',
        ),
        migrations.RemoveField(
            model_name='masterserviceitems',
            name='price_to',
        ),
        migrations.AlterField(
            model_name='masterserviceitems',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='master_service_items',
                to='categories.category',
                verbose_name='Service (subcategory)',
            ),
        ),
        migrations.AddConstraint(
            model_name='masterserviceitems',
            constraint=models.UniqueConstraint(
                fields=('master_service', 'category'),
                name='uniq_masterserviceitem_service_category',
            ),
        ),
        migrations.AddField(
            model_name='masterbusyslot',
            name='master',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='busy_slots',
                to='master.master',
                verbose_name='Master',
            ),
        ),
        migrations.AddField(
            model_name='masterbusyslot',
            name='order',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='master_busy_slot',
                to='order.order',
                verbose_name='Order',
            ),
        ),
        migrations.AddField(
            model_name='masterscheduleday',
            name='master',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='schedule_days',
                to='master.master',
                verbose_name='Master',
            ),
        ),
        migrations.AddConstraint(
            model_name='masterscheduleday',
            constraint=models.UniqueConstraint(fields=('master', 'date'), name='uniq_master_schedule_date'),
        ),
    ]
