# Generated by Django 5.2.6 on 2026-04-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0023_backfill_master_busy_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='service_area_latitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='Base work location latitude'),
        ),
        migrations.AddField(
            model_name='master',
            name='service_area_longitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='Base work location longitude'),
        ),
        migrations.AddField(
            model_name='master',
            name='service_area_radius_miles',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(15, '15 miles (minimum)'), (45, '45 miles (medium)'), (100, '100 miles (extended)')], null=True, verbose_name='Service area radius (miles)'),
        ),
    ]
