# Generated by Django 5.2.6 on 2026-04-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0025_remove_service_area_lat_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=9, help_text='Workshop / service point on map; used with service area radius for distance and visibility.', max_digits=12, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='master',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=9, help_text='Workshop / service point on map; used with service area radius for distance and visibility.', max_digits=12, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='master',
            name='service_area_radius_miles',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(15, '15 miles (minimum)'), (45, '45 miles (medium)'), (100, '100 miles (extended)')], help_text='15 / 45 / 100 miles around latitude/longitude for order matching.', null=True, verbose_name='Service area radius (miles)'),
        ),
    ]
