# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0027_remove_master_name_and_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterscheduleday',
            name='start_time_rest',
            field=models.TimeField(
                blank=True,
                help_text='Optional break start on this day (within working hours).',
                null=True,
                verbose_name='Rest start',
            ),
        ),
        migrations.AddField(
            model_name='masterscheduleday',
            name='time_range_rest',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Break length in hours from start_time_rest (e.g. 1.00 or 1.50).',
                max_digits=5,
                null=True,
                verbose_name='Rest duration (hours)',
            ),
        ),
    ]
