# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0028_masterscheduleday_rest_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterscheduleday',
            name='start_time_rest',
        ),
        migrations.RemoveField(
            model_name='masterscheduleday',
            name='time_range_rest',
        ),
        migrations.AddField(
            model_name='masterbusyslot',
            name='start_time_rest',
            field=models.TimeField(
                blank=True,
                help_text='If set with time_range_rest, marks a daily break; start/end are derived. '
                'Only for manual slots (no order).',
                null=True,
                verbose_name='Rest start',
            ),
        ),
        migrations.AddField(
            model_name='masterbusyslot',
            name='time_range_rest',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Break length from start_time_rest (e.g. 1.00). Used for available-slots break_data.',
                max_digits=5,
                null=True,
                verbose_name='Rest duration (hours)',
            ),
        ),
    ]
