# Generated by Django 5.2.6 on 2026-04-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0029_move_rest_from_schedule_to_busy_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=18, help_text='Workshop / service point on map; used with service area radius for distance and visibility.', max_digits=22, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='master',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=18, help_text='Workshop / service point on map; used with service area radius for distance and visibility.', max_digits=22, null=True, verbose_name='Longitude'),
        ),
    ]
