# Generated by Django 5.0.7 on 2026-05-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0030_alter_lat_lon_decimal_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='stripe_connect_account_id',
            field=models.CharField(blank=True, default='', help_text='acct_… — destination for marketplace payouts.', max_length=64, verbose_name='Stripe Connect account id'),
        ),
    ]
