# Generated by Django 5.0.7 on 2026-06-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0033_master_towing_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterserviceitems',
            name='has_diesel_container_2gal',
            field=models.BooleanField(
                default=False,
                help_text='Required for Fuel Delivery: master confirms a dedicated diesel container.',
                verbose_name='Has separate 2-gallon diesel container',
            ),
        ),
        migrations.AddField(
            model_name='masterserviceitems',
            name='has_gas_container_2gal',
            field=models.BooleanField(
                default=False,
                help_text='Required for Fuel Delivery: master confirms a dedicated gasoline container.',
                verbose_name='Has separate 2-gallon gas container',
            ),
        ),
    ]
